calcurse: fix python3 wrapper
The current Python wrapper for `httplib2` breaks when running e.g.
`./result/bin/calcurse-caldav` with the following error:

```
Traceback (most recent call last):
  File "./result/bin/calcurse-caldav", line 6, in <module>
    import httplib2
ModuleNotFoundError: No module named 'httplib2'
```

The easiest workaround is to use the `wrapPython` tool to properly patch
library path inside the script.